# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ed1ba7183121c17f04beb1b57cda95e0"
name = "instagram-feed-app"
handle = "instagram-feed-app-5"
application_url = "https://travelers-nutten-powerseller-county.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xseelleexx.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://travelers-nutten-powerseller-county.trycloudflare.com/auth/callback",
  "https://travelers-nutten-powerseller-county.trycloudflare.com/auth/shopify/callback",
  "https://travelers-nutten-powerseller-county.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
